
# play around with the IG2 distribution
#############################################

# set up the parameters (change these values and think of why the outcomes changed)
N   = 100000    # number of random draws to be sampled
s   = 1         # scale of IG2 distribution 
nu  = 3         # shape of IG2 distribution

# generate draws from IG2 and compute the characteristics
ig2 = s / rchisq(n = N, df = nu)  # generates N draws from IG2(s, nu)
hist(ig2, breaks = 100)           # plots the histogram of the random variable

mean(ig2)                         # computes the expected value (compare this to s/(nu-2))
s / (nu - 2)                          

var(ig2)                          # computes the variance (compare this to (2/(nu-4))*((s/(nu-2))^2) )
(2 / (nu - 4)) * ((s / (nu - 2))^2)

# what if the variance was generated by a gamma distribution
#############################################

precision_draws = rgamma(n = N, shape = nu, scale = s)
variance_draws  = 1 / precision_draws
hist(variance_draws, breaks = 500) # for nu < 2 this will have a lot of mass close to 0 and a very fat tail
